---
deployment:
  tasks:
    - export DEPLOYPATH=/home/luku8469/public_html/xxx.com
    - /bin/cp -R companyprofile $DEPLOYPATH
    - /bin/cp -R xxxcom $DEPLOYPATH
    - /bin/cp -R static $DEPLOYPATH
    - /bin/cp manage.py $DEPLOYPATH
